# Generated by Django 4.2.8 on 2023-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
